// Code generated by protoc-gen-go. DO NOT EDIT.
// source: graphqlc/descriptor.proto

package graphqlc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The protocol compiler can output a FileDescriptorSet containing the
// .graphql file it parses.
type FileDescriptorSet struct {
	File                 []*FileDescriptorGraphql `protobuf:"bytes,1,rep,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *FileDescriptorSet) Reset()         { *m = FileDescriptorSet{} }
func (m *FileDescriptorSet) String() string { return proto.CompactTextString(m) }
func (*FileDescriptorSet) ProtoMessage()    {}
func (*FileDescriptorSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c0692a5e3de09d, []int{0}
}

func (m *FileDescriptorSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileDescriptorSet.Unmarshal(m, b)
}
func (m *FileDescriptorSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileDescriptorSet.Marshal(b, m, deterministic)
}
func (m *FileDescriptorSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileDescriptorSet.Merge(m, src)
}
func (m *FileDescriptorSet) XXX_Size() int {
	return xxx_messageInfo_FileDescriptorSet.Size(m)
}
func (m *FileDescriptorSet) XXX_DiscardUnknown() {
	xxx_messageInfo_FileDescriptorSet.DiscardUnknown(m)
}

var xxx_messageInfo_FileDescriptorSet proto.InternalMessageInfo

func (m *FileDescriptorSet) GetFile() []*FileDescriptorGraphql {
	if m != nil {
		return m.File
	}
	return nil
}

// Describe a complete .graphql file
type FileDescriptorGraphql struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// All top-level definitions in this file.
	Schema               *SchemaDescriptorProto                      `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	Scalars              []*ScalarTypeDefinitionDescriptorProto      `protobuf:"bytes,3,rep,name=scalars,proto3" json:"scalars,omitempty"`
	Objects              []*ObjectTypeDefinitionDescriptorProto      `protobuf:"bytes,4,rep,name=objects,proto3" json:"objects,omitempty"`
	Interfaces           []*InterfaceTypeDefinitionDescriptorProto   `protobuf:"bytes,5,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	Unions               []*UnionTypeDefinitionDescriptorProto       `protobuf:"bytes,6,rep,name=unions,proto3" json:"unions,omitempty"`
	Enums                []*EnumTypeDefinitionDescriptorProto        `protobuf:"bytes,7,rep,name=enums,proto3" json:"enums,omitempty"`
	InputObjects         []*InputObjectTypeDefinitionDescriptorProto `protobuf:"bytes,8,rep,name=input_objects,json=inputObjects,proto3" json:"input_objects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *FileDescriptorGraphql) Reset()         { *m = FileDescriptorGraphql{} }
func (m *FileDescriptorGraphql) String() string { return proto.CompactTextString(m) }
func (*FileDescriptorGraphql) ProtoMessage()    {}
func (*FileDescriptorGraphql) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c0692a5e3de09d, []int{1}
}

func (m *FileDescriptorGraphql) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileDescriptorGraphql.Unmarshal(m, b)
}
func (m *FileDescriptorGraphql) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileDescriptorGraphql.Marshal(b, m, deterministic)
}
func (m *FileDescriptorGraphql) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileDescriptorGraphql.Merge(m, src)
}
func (m *FileDescriptorGraphql) XXX_Size() int {
	return xxx_messageInfo_FileDescriptorGraphql.Size(m)
}
func (m *FileDescriptorGraphql) XXX_DiscardUnknown() {
	xxx_messageInfo_FileDescriptorGraphql.DiscardUnknown(m)
}

var xxx_messageInfo_FileDescriptorGraphql proto.InternalMessageInfo

func (m *FileDescriptorGraphql) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileDescriptorGraphql) GetSchema() *SchemaDescriptorProto {
	if m != nil {
		return m.Schema
	}
	return nil
}

func (m *FileDescriptorGraphql) GetScalars() []*ScalarTypeDefinitionDescriptorProto {
	if m != nil {
		return m.Scalars
	}
	return nil
}

func (m *FileDescriptorGraphql) GetObjects() []*ObjectTypeDefinitionDescriptorProto {
	if m != nil {
		return m.Objects
	}
	return nil
}

func (m *FileDescriptorGraphql) GetInterfaces() []*InterfaceTypeDefinitionDescriptorProto {
	if m != nil {
		return m.Interfaces
	}
	return nil
}

func (m *FileDescriptorGraphql) GetUnions() []*UnionTypeDefinitionDescriptorProto {
	if m != nil {
		return m.Unions
	}
	return nil
}

func (m *FileDescriptorGraphql) GetEnums() []*EnumTypeDefinitionDescriptorProto {
	if m != nil {
		return m.Enums
	}
	return nil
}

func (m *FileDescriptorGraphql) GetInputObjects() []*InputObjectTypeDefinitionDescriptorProto {
	if m != nil {
		return m.InputObjects
	}
	return nil
}

type SchemaDescriptorProto struct {
	Directives           []*DirectiveDescriptorProto          `protobuf:"bytes,1,rep,name=directives,proto3" json:"directives,omitempty"`
	Query                *ObjectTypeDefinitionDescriptorProto `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Mutation             *ObjectTypeDefinitionDescriptorProto `protobuf:"bytes,3,opt,name=mutation,proto3" json:"mutation,omitempty"`
	Subscription         *ObjectTypeDefinitionDescriptorProto `protobuf:"bytes,4,opt,name=subscription,proto3" json:"subscription,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *SchemaDescriptorProto) Reset()         { *m = SchemaDescriptorProto{} }
func (m *SchemaDescriptorProto) String() string { return proto.CompactTextString(m) }
func (*SchemaDescriptorProto) ProtoMessage()    {}
func (*SchemaDescriptorProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c0692a5e3de09d, []int{2}
}

func (m *SchemaDescriptorProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemaDescriptorProto.Unmarshal(m, b)
}
func (m *SchemaDescriptorProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemaDescriptorProto.Marshal(b, m, deterministic)
}
func (m *SchemaDescriptorProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemaDescriptorProto.Merge(m, src)
}
func (m *SchemaDescriptorProto) XXX_Size() int {
	return xxx_messageInfo_SchemaDescriptorProto.Size(m)
}
func (m *SchemaDescriptorProto) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemaDescriptorProto.DiscardUnknown(m)
}

var xxx_messageInfo_SchemaDescriptorProto proto.InternalMessageInfo

func (m *SchemaDescriptorProto) GetDirectives() []*DirectiveDescriptorProto {
	if m != nil {
		return m.Directives
	}
	return nil
}

func (m *SchemaDescriptorProto) GetQuery() *ObjectTypeDefinitionDescriptorProto {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *SchemaDescriptorProto) GetMutation() *ObjectTypeDefinitionDescriptorProto {
	if m != nil {
		return m.Mutation
	}
	return nil
}

func (m *SchemaDescriptorProto) GetSubscription() *ObjectTypeDefinitionDescriptorProto {
	if m != nil {
		return m.Subscription
	}
	return nil
}

type ScalarTypeDefinitionDescriptorProto struct {
	Description          string                      `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Name                 string                      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Directives           []*DirectiveDescriptorProto `protobuf:"bytes,3,rep,name=directives,proto3" json:"directives,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ScalarTypeDefinitionDescriptorProto) Reset()         { *m = ScalarTypeDefinitionDescriptorProto{} }
func (m *ScalarTypeDefinitionDescriptorProto) String() string { return proto.CompactTextString(m) }
func (*ScalarTypeDefinitionDescriptorProto) ProtoMessage()    {}
func (*ScalarTypeDefinitionDescriptorProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c0692a5e3de09d, []int{3}
}

func (m *ScalarTypeDefinitionDescriptorProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScalarTypeDefinitionDescriptorProto.Unmarshal(m, b)
}
func (m *ScalarTypeDefinitionDescriptorProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScalarTypeDefinitionDescriptorProto.Marshal(b, m, deterministic)
}
func (m *ScalarTypeDefinitionDescriptorProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScalarTypeDefinitionDescriptorProto.Merge(m, src)
}
func (m *ScalarTypeDefinitionDescriptorProto) XXX_Size() int {
	return xxx_messageInfo_ScalarTypeDefinitionDescriptorProto.Size(m)
}
func (m *ScalarTypeDefinitionDescriptorProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ScalarTypeDefinitionDescriptorProto.DiscardUnknown(m)
}

var xxx_messageInfo_ScalarTypeDefinitionDescriptorProto proto.InternalMessageInfo

func (m *ScalarTypeDefinitionDescriptorProto) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ScalarTypeDefinitionDescriptorProto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ScalarTypeDefinitionDescriptorProto) GetDirectives() []*DirectiveDescriptorProto {
	if m != nil {
		return m.Directives
	}
	return nil
}

type ObjectTypeDefinitionDescriptorProto struct {
	Description          string                                    `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Name                 string                                    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Implements           []*InterfaceTypeDefinitionDescriptorProto `protobuf:"bytes,3,rep,name=implements,proto3" json:"implements,omitempty"`
	Directives           []*DirectiveDescriptorProto               `protobuf:"bytes,4,rep,name=directives,proto3" json:"directives,omitempty"`
	Fields               []*FieldDefinitionDescriptorProto         `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *ObjectTypeDefinitionDescriptorProto) Reset()         { *m = ObjectTypeDefinitionDescriptorProto{} }
func (m *ObjectTypeDefinitionDescriptorProto) String() string { return proto.CompactTextString(m) }
func (*ObjectTypeDefinitionDescriptorProto) ProtoMessage()    {}
func (*ObjectTypeDefinitionDescriptorProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c0692a5e3de09d, []int{4}
}

func (m *ObjectTypeDefinitionDescriptorProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectTypeDefinitionDescriptorProto.Unmarshal(m, b)
}
func (m *ObjectTypeDefinitionDescriptorProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectTypeDefinitionDescriptorProto.Marshal(b, m, deterministic)
}
func (m *ObjectTypeDefinitionDescriptorProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectTypeDefinitionDescriptorProto.Merge(m, src)
}
func (m *ObjectTypeDefinitionDescriptorProto) XXX_Size() int {
	return xxx_messageInfo_ObjectTypeDefinitionDescriptorProto.Size(m)
}
func (m *ObjectTypeDefinitionDescriptorProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectTypeDefinitionDescriptorProto.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectTypeDefinitionDescriptorProto proto.InternalMessageInfo

func (m *ObjectTypeDefinitionDescriptorProto) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ObjectTypeDefinitionDescriptorProto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ObjectTypeDefinitionDescriptorProto) GetImplements() []*InterfaceTypeDefinitionDescriptorProto {
	if m != nil {
		return m.Implements
	}
	return nil
}

func (m *ObjectTypeDefinitionDescriptorProto) GetDirectives() []*DirectiveDescriptorProto {
	if m != nil {
		return m.Directives
	}
	return nil
}

func (m *ObjectTypeDefinitionDescriptorProto) GetFields() []*FieldDefinitionDescriptorProto {
	if m != nil {
		return m.Fields
	}
	return nil
}

type InterfaceTypeDefinitionDescriptorProto struct {
	Description          string                            `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Name                 string                            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Directives           []*DirectiveDescriptorProto       `protobuf:"bytes,3,rep,name=directives,proto3" json:"directives,omitempty"`
	Fields               []*FieldDefinitionDescriptorProto `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *InterfaceTypeDefinitionDescriptorProto) Reset() {
	*m = InterfaceTypeDefinitionDescriptorProto{}
}
func (m *InterfaceTypeDefinitionDescriptorProto) String() string { return proto.CompactTextString(m) }
func (*InterfaceTypeDefinitionDescriptorProto) ProtoMessage()    {}
func (*InterfaceTypeDefinitionDescriptorProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c0692a5e3de09d, []int{5}
}

func (m *InterfaceTypeDefinitionDescriptorProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterfaceTypeDefinitionDescriptorProto.Unmarshal(m, b)
}
func (m *InterfaceTypeDefinitionDescriptorProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterfaceTypeDefinitionDescriptorProto.Marshal(b, m, deterministic)
}
func (m *InterfaceTypeDefinitionDescriptorProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfaceTypeDefinitionDescriptorProto.Merge(m, src)
}
func (m *InterfaceTypeDefinitionDescriptorProto) XXX_Size() int {
	return xxx_messageInfo_InterfaceTypeDefinitionDescriptorProto.Size(m)
}
func (m *InterfaceTypeDefinitionDescriptorProto) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfaceTypeDefinitionDescriptorProto.DiscardUnknown(m)
}

var xxx_messageInfo_InterfaceTypeDefinitionDescriptorProto proto.InternalMessageInfo

func (m *InterfaceTypeDefinitionDescriptorProto) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *InterfaceTypeDefinitionDescriptorProto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InterfaceTypeDefinitionDescriptorProto) GetDirectives() []*DirectiveDescriptorProto {
	if m != nil {
		return m.Directives
	}
	return nil
}

func (m *InterfaceTypeDefinitionDescriptorProto) GetFields() []*FieldDefinitionDescriptorProto {
	if m != nil {
		return m.Fields
	}
	return nil
}

type UnionTypeDefinitionDescriptorProto struct {
	Description          string                      `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Name                 string                      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Directives           []*DirectiveDescriptorProto `protobuf:"bytes,3,rep,name=directives,proto3" json:"directives,omitempty"`
	MemberTypes          []*NamedTypeDescriptorProto `protobuf:"bytes,4,rep,name=member_types,json=memberTypes,proto3" json:"member_types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *UnionTypeDefinitionDescriptorProto) Reset()         { *m = UnionTypeDefinitionDescriptorProto{} }
func (m *UnionTypeDefinitionDescriptorProto) String() string { return proto.CompactTextString(m) }
func (*UnionTypeDefinitionDescriptorProto) ProtoMessage()    {}
func (*UnionTypeDefinitionDescriptorProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c0692a5e3de09d, []int{6}
}

func (m *UnionTypeDefinitionDescriptorProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnionTypeDefinitionDescriptorProto.Unmarshal(m, b)
}
func (m *UnionTypeDefinitionDescriptorProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnionTypeDefinitionDescriptorProto.Marshal(b, m, deterministic)
}
func (m *UnionTypeDefinitionDescriptorProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnionTypeDefinitionDescriptorProto.Merge(m, src)
}
func (m *UnionTypeDefinitionDescriptorProto) XXX_Size() int {
	return xxx_messageInfo_UnionTypeDefinitionDescriptorProto.Size(m)
}
func (m *UnionTypeDefinitionDescriptorProto) XXX_DiscardUnknown() {
	xxx_messageInfo_UnionTypeDefinitionDescriptorProto.DiscardUnknown(m)
}

var xxx_messageInfo_UnionTypeDefinitionDescriptorProto proto.InternalMessageInfo

func (m *UnionTypeDefinitionDescriptorProto) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UnionTypeDefinitionDescriptorProto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UnionTypeDefinitionDescriptorProto) GetDirectives() []*DirectiveDescriptorProto {
	if m != nil {
		return m.Directives
	}
	return nil
}

func (m *UnionTypeDefinitionDescriptorProto) GetMemberTypes() []*NamedTypeDescriptorProto {
	if m != nil {
		return m.MemberTypes
	}
	return nil
}

type EnumTypeDefinitionDescriptorProto struct {
	Description          string                            `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Name                 string                            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Directives           []*DirectiveDescriptorProto       `protobuf:"bytes,3,rep,name=directives,proto3" json:"directives,omitempty"`
	Values               []*EnumValueDefinitionDescription `protobuf:"bytes,4,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *EnumTypeDefinitionDescriptorProto) Reset()         { *m = EnumTypeDefinitionDescriptorProto{} }
func (m *EnumTypeDefinitionDescriptorProto) String() string { return proto.CompactTextString(m) }
func (*EnumTypeDefinitionDescriptorProto) ProtoMessage()    {}
func (*EnumTypeDefinitionDescriptorProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c0692a5e3de09d, []int{7}
}

func (m *EnumTypeDefinitionDescriptorProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumTypeDefinitionDescriptorProto.Unmarshal(m, b)
}
func (m *EnumTypeDefinitionDescriptorProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumTypeDefinitionDescriptorProto.Marshal(b, m, deterministic)
}
func (m *EnumTypeDefinitionDescriptorProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumTypeDefinitionDescriptorProto.Merge(m, src)
}
func (m *EnumTypeDefinitionDescriptorProto) XXX_Size() int {
	return xxx_messageInfo_EnumTypeDefinitionDescriptorProto.Size(m)
}
func (m *EnumTypeDefinitionDescriptorProto) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumTypeDefinitionDescriptorProto.DiscardUnknown(m)
}

var xxx_messageInfo_EnumTypeDefinitionDescriptorProto proto.InternalMessageInfo

func (m *EnumTypeDefinitionDescriptorProto) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *EnumTypeDefinitionDescriptorProto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EnumTypeDefinitionDescriptorProto) GetDirectives() []*DirectiveDescriptorProto {
	if m != nil {
		return m.Directives
	}
	return nil
}

func (m *EnumTypeDefinitionDescriptorProto) GetValues() []*EnumValueDefinitionDescription {
	if m != nil {
		return m.Values
	}
	return nil
}

type InputObjectTypeDefinitionDescriptorProto struct {
	Description          string                                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Name                 string                                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Directives           []*DirectiveDescriptorProto            `protobuf:"bytes,3,rep,name=directives,proto3" json:"directives,omitempty"`
	Fields               []*InputValueDefinitionDescriptorProto `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *InputObjectTypeDefinitionDescriptorProto) Reset() {
	*m = InputObjectTypeDefinitionDescriptorProto{}
}
func (m *InputObjectTypeDefinitionDescriptorProto) String() string { return proto.CompactTextString(m) }
func (*InputObjectTypeDefinitionDescriptorProto) ProtoMessage()    {}
func (*InputObjectTypeDefinitionDescriptorProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c0692a5e3de09d, []int{8}
}

func (m *InputObjectTypeDefinitionDescriptorProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputObjectTypeDefinitionDescriptorProto.Unmarshal(m, b)
}
func (m *InputObjectTypeDefinitionDescriptorProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputObjectTypeDefinitionDescriptorProto.Marshal(b, m, deterministic)
}
func (m *InputObjectTypeDefinitionDescriptorProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputObjectTypeDefinitionDescriptorProto.Merge(m, src)
}
func (m *InputObjectTypeDefinitionDescriptorProto) XXX_Size() int {
	return xxx_messageInfo_InputObjectTypeDefinitionDescriptorProto.Size(m)
}
func (m *InputObjectTypeDefinitionDescriptorProto) XXX_DiscardUnknown() {
	xxx_messageInfo_InputObjectTypeDefinitionDescriptorProto.DiscardUnknown(m)
}

var xxx_messageInfo_InputObjectTypeDefinitionDescriptorProto proto.InternalMessageInfo

func (m *InputObjectTypeDefinitionDescriptorProto) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *InputObjectTypeDefinitionDescriptorProto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InputObjectTypeDefinitionDescriptorProto) GetDirectives() []*DirectiveDescriptorProto {
	if m != nil {
		return m.Directives
	}
	return nil
}

func (m *InputObjectTypeDefinitionDescriptorProto) GetFields() []*InputValueDefinitionDescriptorProto {
	if m != nil {
		return m.Fields
	}
	return nil
}

type EnumValueDefinitionDescription struct {
	Description          string                      `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Value                string                      `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Directives           []*DirectiveDescriptorProto `protobuf:"bytes,3,rep,name=directives,proto3" json:"directives,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *EnumValueDefinitionDescription) Reset()         { *m = EnumValueDefinitionDescription{} }
func (m *EnumValueDefinitionDescription) String() string { return proto.CompactTextString(m) }
func (*EnumValueDefinitionDescription) ProtoMessage()    {}
func (*EnumValueDefinitionDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c0692a5e3de09d, []int{9}
}

func (m *EnumValueDefinitionDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumValueDefinitionDescription.Unmarshal(m, b)
}
func (m *EnumValueDefinitionDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumValueDefinitionDescription.Marshal(b, m, deterministic)
}
func (m *EnumValueDefinitionDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumValueDefinitionDescription.Merge(m, src)
}
func (m *EnumValueDefinitionDescription) XXX_Size() int {
	return xxx_messageInfo_EnumValueDefinitionDescription.Size(m)
}
func (m *EnumValueDefinitionDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumValueDefinitionDescription.DiscardUnknown(m)
}

var xxx_messageInfo_EnumValueDefinitionDescription proto.InternalMessageInfo

func (m *EnumValueDefinitionDescription) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *EnumValueDefinitionDescription) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *EnumValueDefinitionDescription) GetDirectives() []*DirectiveDescriptorProto {
	if m != nil {
		return m.Directives
	}
	return nil
}

type FieldDefinitionDescriptorProto struct {
	Description          string                                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Name                 string                                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Arguments            []*InputValueDefinitionDescriptorProto `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty"`
	Type                 *TypeDescriptorProto                   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Directives           []*DirectiveDescriptorProto            `protobuf:"bytes,5,rep,name=directives,proto3" json:"directives,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *FieldDefinitionDescriptorProto) Reset()         { *m = FieldDefinitionDescriptorProto{} }
func (m *FieldDefinitionDescriptorProto) String() string { return proto.CompactTextString(m) }
func (*FieldDefinitionDescriptorProto) ProtoMessage()    {}
func (*FieldDefinitionDescriptorProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c0692a5e3de09d, []int{10}
}

func (m *FieldDefinitionDescriptorProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldDefinitionDescriptorProto.Unmarshal(m, b)
}
func (m *FieldDefinitionDescriptorProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldDefinitionDescriptorProto.Marshal(b, m, deterministic)
}
func (m *FieldDefinitionDescriptorProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldDefinitionDescriptorProto.Merge(m, src)
}
func (m *FieldDefinitionDescriptorProto) XXX_Size() int {
	return xxx_messageInfo_FieldDefinitionDescriptorProto.Size(m)
}
func (m *FieldDefinitionDescriptorProto) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldDefinitionDescriptorProto.DiscardUnknown(m)
}

var xxx_messageInfo_FieldDefinitionDescriptorProto proto.InternalMessageInfo

func (m *FieldDefinitionDescriptorProto) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *FieldDefinitionDescriptorProto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FieldDefinitionDescriptorProto) GetArguments() []*InputValueDefinitionDescriptorProto {
	if m != nil {
		return m.Arguments
	}
	return nil
}

func (m *FieldDefinitionDescriptorProto) GetType() *TypeDescriptorProto {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *FieldDefinitionDescriptorProto) GetDirectives() []*DirectiveDescriptorProto {
	if m != nil {
		return m.Directives
	}
	return nil
}

type InputValueDefinitionDescriptorProto struct {
	Description          string                      `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Name                 string                      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 *TypeDescriptorProto        `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	DefaultValue         *ValueDescriptorProto       `protobuf:"bytes,4,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Directives           []*DirectiveDescriptorProto `protobuf:"bytes,5,rep,name=directives,proto3" json:"directives,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *InputValueDefinitionDescriptorProto) Reset()         { *m = InputValueDefinitionDescriptorProto{} }
func (m *InputValueDefinitionDescriptorProto) String() string { return proto.CompactTextString(m) }
func (*InputValueDefinitionDescriptorProto) ProtoMessage()    {}
func (*InputValueDefinitionDescriptorProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c0692a5e3de09d, []int{11}
}

func (m *InputValueDefinitionDescriptorProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputValueDefinitionDescriptorProto.Unmarshal(m, b)
}
func (m *InputValueDefinitionDescriptorProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputValueDefinitionDescriptorProto.Marshal(b, m, deterministic)
}
func (m *InputValueDefinitionDescriptorProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputValueDefinitionDescriptorProto.Merge(m, src)
}
func (m *InputValueDefinitionDescriptorProto) XXX_Size() int {
	return xxx_messageInfo_InputValueDefinitionDescriptorProto.Size(m)
}
func (m *InputValueDefinitionDescriptorProto) XXX_DiscardUnknown() {
	xxx_messageInfo_InputValueDefinitionDescriptorProto.DiscardUnknown(m)
}

var xxx_messageInfo_InputValueDefinitionDescriptorProto proto.InternalMessageInfo

func (m *InputValueDefinitionDescriptorProto) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *InputValueDefinitionDescriptorProto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InputValueDefinitionDescriptorProto) GetType() *TypeDescriptorProto {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *InputValueDefinitionDescriptorProto) GetDefaultValue() *ValueDescriptorProto {
	if m != nil {
		return m.DefaultValue
	}
	return nil
}

func (m *InputValueDefinitionDescriptorProto) GetDirectives() []*DirectiveDescriptorProto {
	if m != nil {
		return m.Directives
	}
	return nil
}

type TypeDescriptorProto struct {
	// Types that are valid to be assigned to Type:
	//	*TypeDescriptorProto_NamedType
	//	*TypeDescriptorProto_ListType
	//	*TypeDescriptorProto_NonNullType
	Type                 isTypeDescriptorProto_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *TypeDescriptorProto) Reset()         { *m = TypeDescriptorProto{} }
func (m *TypeDescriptorProto) String() string { return proto.CompactTextString(m) }
func (*TypeDescriptorProto) ProtoMessage()    {}
func (*TypeDescriptorProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c0692a5e3de09d, []int{12}
}

func (m *TypeDescriptorProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeDescriptorProto.Unmarshal(m, b)
}
func (m *TypeDescriptorProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeDescriptorProto.Marshal(b, m, deterministic)
}
func (m *TypeDescriptorProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeDescriptorProto.Merge(m, src)
}
func (m *TypeDescriptorProto) XXX_Size() int {
	return xxx_messageInfo_TypeDescriptorProto.Size(m)
}
func (m *TypeDescriptorProto) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeDescriptorProto.DiscardUnknown(m)
}

var xxx_messageInfo_TypeDescriptorProto proto.InternalMessageInfo

type isTypeDescriptorProto_Type interface {
	isTypeDescriptorProto_Type()
}

type TypeDescriptorProto_NamedType struct {
	NamedType *NamedTypeDescriptorProto `protobuf:"bytes,1,opt,name=named_type,json=namedType,proto3,oneof"`
}

type TypeDescriptorProto_ListType struct {
	ListType *ListTypeDescriptorProto `protobuf:"bytes,2,opt,name=list_type,json=listType,proto3,oneof"`
}

type TypeDescriptorProto_NonNullType struct {
	NonNullType *NonNullTypeDescriptorProto `protobuf:"bytes,3,opt,name=non_null_type,json=nonNullType,proto3,oneof"`
}

func (*TypeDescriptorProto_NamedType) isTypeDescriptorProto_Type() {}

func (*TypeDescriptorProto_ListType) isTypeDescriptorProto_Type() {}

func (*TypeDescriptorProto_NonNullType) isTypeDescriptorProto_Type() {}

func (m *TypeDescriptorProto) GetType() isTypeDescriptorProto_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *TypeDescriptorProto) GetNamedType() *NamedTypeDescriptorProto {
	if x, ok := m.GetType().(*TypeDescriptorProto_NamedType); ok {
		return x.NamedType
	}
	return nil
}

func (m *TypeDescriptorProto) GetListType() *ListTypeDescriptorProto {
	if x, ok := m.GetType().(*TypeDescriptorProto_ListType); ok {
		return x.ListType
	}
	return nil
}

func (m *TypeDescriptorProto) GetNonNullType() *NonNullTypeDescriptorProto {
	if x, ok := m.GetType().(*TypeDescriptorProto_NonNullType); ok {
		return x.NonNullType
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TypeDescriptorProto) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TypeDescriptorProto_NamedType)(nil),
		(*TypeDescriptorProto_ListType)(nil),
		(*TypeDescriptorProto_NonNullType)(nil),
	}
}

type NamedTypeDescriptorProto struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NamedTypeDescriptorProto) Reset()         { *m = NamedTypeDescriptorProto{} }
func (m *NamedTypeDescriptorProto) String() string { return proto.CompactTextString(m) }
func (*NamedTypeDescriptorProto) ProtoMessage()    {}
func (*NamedTypeDescriptorProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c0692a5e3de09d, []int{13}
}

func (m *NamedTypeDescriptorProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamedTypeDescriptorProto.Unmarshal(m, b)
}
func (m *NamedTypeDescriptorProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamedTypeDescriptorProto.Marshal(b, m, deterministic)
}
func (m *NamedTypeDescriptorProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamedTypeDescriptorProto.Merge(m, src)
}
func (m *NamedTypeDescriptorProto) XXX_Size() int {
	return xxx_messageInfo_NamedTypeDescriptorProto.Size(m)
}
func (m *NamedTypeDescriptorProto) XXX_DiscardUnknown() {
	xxx_messageInfo_NamedTypeDescriptorProto.DiscardUnknown(m)
}

var xxx_messageInfo_NamedTypeDescriptorProto proto.InternalMessageInfo

func (m *NamedTypeDescriptorProto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListTypeDescriptorProto struct {
	Type                 *TypeDescriptorProto `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListTypeDescriptorProto) Reset()         { *m = ListTypeDescriptorProto{} }
func (m *ListTypeDescriptorProto) String() string { return proto.CompactTextString(m) }
func (*ListTypeDescriptorProto) ProtoMessage()    {}
func (*ListTypeDescriptorProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c0692a5e3de09d, []int{14}
}

func (m *ListTypeDescriptorProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTypeDescriptorProto.Unmarshal(m, b)
}
func (m *ListTypeDescriptorProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTypeDescriptorProto.Marshal(b, m, deterministic)
}
func (m *ListTypeDescriptorProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTypeDescriptorProto.Merge(m, src)
}
func (m *ListTypeDescriptorProto) XXX_Size() int {
	return xxx_messageInfo_ListTypeDescriptorProto.Size(m)
}
func (m *ListTypeDescriptorProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTypeDescriptorProto.DiscardUnknown(m)
}

var xxx_messageInfo_ListTypeDescriptorProto proto.InternalMessageInfo

func (m *ListTypeDescriptorProto) GetType() *TypeDescriptorProto {
	if m != nil {
		return m.Type
	}
	return nil
}

type NonNullTypeDescriptorProto struct {
	// Types that are valid to be assigned to Type:
	//	*NonNullTypeDescriptorProto_NamedType
	//	*NonNullTypeDescriptorProto_ListType
	Type                 isNonNullTypeDescriptorProto_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *NonNullTypeDescriptorProto) Reset()         { *m = NonNullTypeDescriptorProto{} }
func (m *NonNullTypeDescriptorProto) String() string { return proto.CompactTextString(m) }
func (*NonNullTypeDescriptorProto) ProtoMessage()    {}
func (*NonNullTypeDescriptorProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c0692a5e3de09d, []int{15}
}

func (m *NonNullTypeDescriptorProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NonNullTypeDescriptorProto.Unmarshal(m, b)
}
func (m *NonNullTypeDescriptorProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NonNullTypeDescriptorProto.Marshal(b, m, deterministic)
}
func (m *NonNullTypeDescriptorProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NonNullTypeDescriptorProto.Merge(m, src)
}
func (m *NonNullTypeDescriptorProto) XXX_Size() int {
	return xxx_messageInfo_NonNullTypeDescriptorProto.Size(m)
}
func (m *NonNullTypeDescriptorProto) XXX_DiscardUnknown() {
	xxx_messageInfo_NonNullTypeDescriptorProto.DiscardUnknown(m)
}

var xxx_messageInfo_NonNullTypeDescriptorProto proto.InternalMessageInfo

type isNonNullTypeDescriptorProto_Type interface {
	isNonNullTypeDescriptorProto_Type()
}

type NonNullTypeDescriptorProto_NamedType struct {
	NamedType *NamedTypeDescriptorProto `protobuf:"bytes,1,opt,name=named_type,json=namedType,proto3,oneof"`
}

type NonNullTypeDescriptorProto_ListType struct {
	ListType *ListTypeDescriptorProto `protobuf:"bytes,2,opt,name=list_type,json=listType,proto3,oneof"`
}

func (*NonNullTypeDescriptorProto_NamedType) isNonNullTypeDescriptorProto_Type() {}

func (*NonNullTypeDescriptorProto_ListType) isNonNullTypeDescriptorProto_Type() {}

func (m *NonNullTypeDescriptorProto) GetType() isNonNullTypeDescriptorProto_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *NonNullTypeDescriptorProto) GetNamedType() *NamedTypeDescriptorProto {
	if x, ok := m.GetType().(*NonNullTypeDescriptorProto_NamedType); ok {
		return x.NamedType
	}
	return nil
}

func (m *NonNullTypeDescriptorProto) GetListType() *ListTypeDescriptorProto {
	if x, ok := m.GetType().(*NonNullTypeDescriptorProto_ListType); ok {
		return x.ListType
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*NonNullTypeDescriptorProto) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*NonNullTypeDescriptorProto_NamedType)(nil),
		(*NonNullTypeDescriptorProto_ListType)(nil),
	}
}

type DirectiveDescriptorProto struct {
	Name                 string                     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Arguments            []*ArgumentDescriptorProto `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *DirectiveDescriptorProto) Reset()         { *m = DirectiveDescriptorProto{} }
func (m *DirectiveDescriptorProto) String() string { return proto.CompactTextString(m) }
func (*DirectiveDescriptorProto) ProtoMessage()    {}
func (*DirectiveDescriptorProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c0692a5e3de09d, []int{16}
}

func (m *DirectiveDescriptorProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectiveDescriptorProto.Unmarshal(m, b)
}
func (m *DirectiveDescriptorProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectiveDescriptorProto.Marshal(b, m, deterministic)
}
func (m *DirectiveDescriptorProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectiveDescriptorProto.Merge(m, src)
}
func (m *DirectiveDescriptorProto) XXX_Size() int {
	return xxx_messageInfo_DirectiveDescriptorProto.Size(m)
}
func (m *DirectiveDescriptorProto) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectiveDescriptorProto.DiscardUnknown(m)
}

var xxx_messageInfo_DirectiveDescriptorProto proto.InternalMessageInfo

func (m *DirectiveDescriptorProto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DirectiveDescriptorProto) GetArguments() []*ArgumentDescriptorProto {
	if m != nil {
		return m.Arguments
	}
	return nil
}

type ArgumentDescriptorProto struct {
	Name                 string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                *ValueDescriptorProto `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ArgumentDescriptorProto) Reset()         { *m = ArgumentDescriptorProto{} }
func (m *ArgumentDescriptorProto) String() string { return proto.CompactTextString(m) }
func (*ArgumentDescriptorProto) ProtoMessage()    {}
func (*ArgumentDescriptorProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c0692a5e3de09d, []int{17}
}

func (m *ArgumentDescriptorProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArgumentDescriptorProto.Unmarshal(m, b)
}
func (m *ArgumentDescriptorProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArgumentDescriptorProto.Marshal(b, m, deterministic)
}
func (m *ArgumentDescriptorProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArgumentDescriptorProto.Merge(m, src)
}
func (m *ArgumentDescriptorProto) XXX_Size() int {
	return xxx_messageInfo_ArgumentDescriptorProto.Size(m)
}
func (m *ArgumentDescriptorProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ArgumentDescriptorProto.DiscardUnknown(m)
}

var xxx_messageInfo_ArgumentDescriptorProto proto.InternalMessageInfo

func (m *ArgumentDescriptorProto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ArgumentDescriptorProto) GetValue() *ValueDescriptorProto {
	if m != nil {
		return m.Value
	}
	return nil
}

type ValueDescriptorProto struct {
	// Types that are valid to be assigned to Value:
	//	*ValueDescriptorProto_VariableValue
	//	*ValueDescriptorProto_IntValue
	//	*ValueDescriptorProto_FloatValue
	//	*ValueDescriptorProto_BooleanValue
	//	*ValueDescriptorProto_StringValue
	//	*ValueDescriptorProto_NullValue
	//	*ValueDescriptorProto_EnumValue
	//	*ValueDescriptorProto_ListValue
	//	*ValueDescriptorProto_ObjectValue
	Value                isValueDescriptorProto_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ValueDescriptorProto) Reset()         { *m = ValueDescriptorProto{} }
func (m *ValueDescriptorProto) String() string { return proto.CompactTextString(m) }
func (*ValueDescriptorProto) ProtoMessage()    {}
func (*ValueDescriptorProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c0692a5e3de09d, []int{18}
}

func (m *ValueDescriptorProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValueDescriptorProto.Unmarshal(m, b)
}
func (m *ValueDescriptorProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValueDescriptorProto.Marshal(b, m, deterministic)
}
func (m *ValueDescriptorProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValueDescriptorProto.Merge(m, src)
}
func (m *ValueDescriptorProto) XXX_Size() int {
	return xxx_messageInfo_ValueDescriptorProto.Size(m)
}
func (m *ValueDescriptorProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ValueDescriptorProto.DiscardUnknown(m)
}

var xxx_messageInfo_ValueDescriptorProto proto.InternalMessageInfo

type isValueDescriptorProto_Value interface {
	isValueDescriptorProto_Value()
}

type ValueDescriptorProto_VariableValue struct {
	VariableValue *VariableDescriptorProto `protobuf:"bytes,2,opt,name=variable_value,json=variableValue,proto3,oneof"`
}

type ValueDescriptorProto_IntValue struct {
	IntValue int32 `protobuf:"varint,3,opt,name=int_value,json=intValue,proto3,oneof"`
}

type ValueDescriptorProto_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,4,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type ValueDescriptorProto_BooleanValue struct {
	BooleanValue bool `protobuf:"varint,5,opt,name=boolean_value,json=booleanValue,proto3,oneof"`
}

type ValueDescriptorProto_StringValue struct {
	StringValue string `protobuf:"bytes,6,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type ValueDescriptorProto_NullValue struct {
	NullValue *NullValueDescriptorProto `protobuf:"bytes,7,opt,name=null_value,json=nullValue,proto3,oneof"`
}

type ValueDescriptorProto_EnumValue struct {
	EnumValue *EnumValueDescriptorProto `protobuf:"bytes,8,opt,name=enum_value,json=enumValue,proto3,oneof"`
}

type ValueDescriptorProto_ListValue struct {
	ListValue *ListValueDescriptorProto `protobuf:"bytes,9,opt,name=list_value,json=listValue,proto3,oneof"`
}

type ValueDescriptorProto_ObjectValue struct {
	ObjectValue *ObjectValueDescriptorProto `protobuf:"bytes,10,opt,name=object_value,json=objectValue,proto3,oneof"`
}

func (*ValueDescriptorProto_VariableValue) isValueDescriptorProto_Value() {}

func (*ValueDescriptorProto_IntValue) isValueDescriptorProto_Value() {}

func (*ValueDescriptorProto_FloatValue) isValueDescriptorProto_Value() {}

func (*ValueDescriptorProto_BooleanValue) isValueDescriptorProto_Value() {}

func (*ValueDescriptorProto_StringValue) isValueDescriptorProto_Value() {}

func (*ValueDescriptorProto_NullValue) isValueDescriptorProto_Value() {}

func (*ValueDescriptorProto_EnumValue) isValueDescriptorProto_Value() {}

func (*ValueDescriptorProto_ListValue) isValueDescriptorProto_Value() {}

func (*ValueDescriptorProto_ObjectValue) isValueDescriptorProto_Value() {}

func (m *ValueDescriptorProto) GetValue() isValueDescriptorProto_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ValueDescriptorProto) GetVariableValue() *VariableDescriptorProto {
	if x, ok := m.GetValue().(*ValueDescriptorProto_VariableValue); ok {
		return x.VariableValue
	}
	return nil
}

func (m *ValueDescriptorProto) GetIntValue() int32 {
	if x, ok := m.GetValue().(*ValueDescriptorProto_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (m *ValueDescriptorProto) GetFloatValue() float32 {
	if x, ok := m.GetValue().(*ValueDescriptorProto_FloatValue); ok {
		return x.FloatValue
	}
	return 0
}

func (m *ValueDescriptorProto) GetBooleanValue() bool {
	if x, ok := m.GetValue().(*ValueDescriptorProto_BooleanValue); ok {
		return x.BooleanValue
	}
	return false
}

func (m *ValueDescriptorProto) GetStringValue() string {
	if x, ok := m.GetValue().(*ValueDescriptorProto_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *ValueDescriptorProto) GetNullValue() *NullValueDescriptorProto {
	if x, ok := m.GetValue().(*ValueDescriptorProto_NullValue); ok {
		return x.NullValue
	}
	return nil
}

func (m *ValueDescriptorProto) GetEnumValue() *EnumValueDescriptorProto {
	if x, ok := m.GetValue().(*ValueDescriptorProto_EnumValue); ok {
		return x.EnumValue
	}
	return nil
}

func (m *ValueDescriptorProto) GetListValue() *ListValueDescriptorProto {
	if x, ok := m.GetValue().(*ValueDescriptorProto_ListValue); ok {
		return x.ListValue
	}
	return nil
}

func (m *ValueDescriptorProto) GetObjectValue() *ObjectValueDescriptorProto {
	if x, ok := m.GetValue().(*ValueDescriptorProto_ObjectValue); ok {
		return x.ObjectValue
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ValueDescriptorProto) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ValueDescriptorProto_VariableValue)(nil),
		(*ValueDescriptorProto_IntValue)(nil),
		(*ValueDescriptorProto_FloatValue)(nil),
		(*ValueDescriptorProto_BooleanValue)(nil),
		(*ValueDescriptorProto_StringValue)(nil),
		(*ValueDescriptorProto_NullValue)(nil),
		(*ValueDescriptorProto_EnumValue)(nil),
		(*ValueDescriptorProto_ListValue)(nil),
		(*ValueDescriptorProto_ObjectValue)(nil),
	}
}

type VariableDescriptorProto struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VariableDescriptorProto) Reset()         { *m = VariableDescriptorProto{} }
func (m *VariableDescriptorProto) String() string { return proto.CompactTextString(m) }
func (*VariableDescriptorProto) ProtoMessage()    {}
func (*VariableDescriptorProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c0692a5e3de09d, []int{19}
}

func (m *VariableDescriptorProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VariableDescriptorProto.Unmarshal(m, b)
}
func (m *VariableDescriptorProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VariableDescriptorProto.Marshal(b, m, deterministic)
}
func (m *VariableDescriptorProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VariableDescriptorProto.Merge(m, src)
}
func (m *VariableDescriptorProto) XXX_Size() int {
	return xxx_messageInfo_VariableDescriptorProto.Size(m)
}
func (m *VariableDescriptorProto) XXX_DiscardUnknown() {
	xxx_messageInfo_VariableDescriptorProto.DiscardUnknown(m)
}

var xxx_messageInfo_VariableDescriptorProto proto.InternalMessageInfo

func (m *VariableDescriptorProto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type NullValueDescriptorProto struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NullValueDescriptorProto) Reset()         { *m = NullValueDescriptorProto{} }
func (m *NullValueDescriptorProto) String() string { return proto.CompactTextString(m) }
func (*NullValueDescriptorProto) ProtoMessage()    {}
func (*NullValueDescriptorProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c0692a5e3de09d, []int{20}
}

func (m *NullValueDescriptorProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullValueDescriptorProto.Unmarshal(m, b)
}
func (m *NullValueDescriptorProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullValueDescriptorProto.Marshal(b, m, deterministic)
}
func (m *NullValueDescriptorProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullValueDescriptorProto.Merge(m, src)
}
func (m *NullValueDescriptorProto) XXX_Size() int {
	return xxx_messageInfo_NullValueDescriptorProto.Size(m)
}
func (m *NullValueDescriptorProto) XXX_DiscardUnknown() {
	xxx_messageInfo_NullValueDescriptorProto.DiscardUnknown(m)
}

var xxx_messageInfo_NullValueDescriptorProto proto.InternalMessageInfo

func (m *NullValueDescriptorProto) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type EnumValueDescriptorProto struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnumValueDescriptorProto) Reset()         { *m = EnumValueDescriptorProto{} }
func (m *EnumValueDescriptorProto) String() string { return proto.CompactTextString(m) }
func (*EnumValueDescriptorProto) ProtoMessage()    {}
func (*EnumValueDescriptorProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c0692a5e3de09d, []int{21}
}

func (m *EnumValueDescriptorProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumValueDescriptorProto.Unmarshal(m, b)
}
func (m *EnumValueDescriptorProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumValueDescriptorProto.Marshal(b, m, deterministic)
}
func (m *EnumValueDescriptorProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumValueDescriptorProto.Merge(m, src)
}
func (m *EnumValueDescriptorProto) XXX_Size() int {
	return xxx_messageInfo_EnumValueDescriptorProto.Size(m)
}
func (m *EnumValueDescriptorProto) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumValueDescriptorProto.DiscardUnknown(m)
}

var xxx_messageInfo_EnumValueDescriptorProto proto.InternalMessageInfo

func (m *EnumValueDescriptorProto) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ListValueDescriptorProto struct {
	Values               []*ValueDescriptorProto `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ListValueDescriptorProto) Reset()         { *m = ListValueDescriptorProto{} }
func (m *ListValueDescriptorProto) String() string { return proto.CompactTextString(m) }
func (*ListValueDescriptorProto) ProtoMessage()    {}
func (*ListValueDescriptorProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c0692a5e3de09d, []int{22}
}

func (m *ListValueDescriptorProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListValueDescriptorProto.Unmarshal(m, b)
}
func (m *ListValueDescriptorProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListValueDescriptorProto.Marshal(b, m, deterministic)
}
func (m *ListValueDescriptorProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListValueDescriptorProto.Merge(m, src)
}
func (m *ListValueDescriptorProto) XXX_Size() int {
	return xxx_messageInfo_ListValueDescriptorProto.Size(m)
}
func (m *ListValueDescriptorProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ListValueDescriptorProto.DiscardUnknown(m)
}

var xxx_messageInfo_ListValueDescriptorProto proto.InternalMessageInfo

func (m *ListValueDescriptorProto) GetValues() []*ValueDescriptorProto {
	if m != nil {
		return m.Values
	}
	return nil
}

type ObjectValueDescriptorProto struct {
	Fields               []*ObjectFieldDescriptorProto `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ObjectValueDescriptorProto) Reset()         { *m = ObjectValueDescriptorProto{} }
func (m *ObjectValueDescriptorProto) String() string { return proto.CompactTextString(m) }
func (*ObjectValueDescriptorProto) ProtoMessage()    {}
func (*ObjectValueDescriptorProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c0692a5e3de09d, []int{23}
}

func (m *ObjectValueDescriptorProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectValueDescriptorProto.Unmarshal(m, b)
}
func (m *ObjectValueDescriptorProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectValueDescriptorProto.Marshal(b, m, deterministic)
}
func (m *ObjectValueDescriptorProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectValueDescriptorProto.Merge(m, src)
}
func (m *ObjectValueDescriptorProto) XXX_Size() int {
	return xxx_messageInfo_ObjectValueDescriptorProto.Size(m)
}
func (m *ObjectValueDescriptorProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectValueDescriptorProto.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectValueDescriptorProto proto.InternalMessageInfo

func (m *ObjectValueDescriptorProto) GetFields() []*ObjectFieldDescriptorProto {
	if m != nil {
		return m.Fields
	}
	return nil
}

type ObjectFieldDescriptorProto struct {
	Name                 string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                *ValueDescriptorProto `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ObjectFieldDescriptorProto) Reset()         { *m = ObjectFieldDescriptorProto{} }
func (m *ObjectFieldDescriptorProto) String() string { return proto.CompactTextString(m) }
func (*ObjectFieldDescriptorProto) ProtoMessage()    {}
func (*ObjectFieldDescriptorProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c0692a5e3de09d, []int{24}
}

func (m *ObjectFieldDescriptorProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectFieldDescriptorProto.Unmarshal(m, b)
}
func (m *ObjectFieldDescriptorProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectFieldDescriptorProto.Marshal(b, m, deterministic)
}
func (m *ObjectFieldDescriptorProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectFieldDescriptorProto.Merge(m, src)
}
func (m *ObjectFieldDescriptorProto) XXX_Size() int {
	return xxx_messageInfo_ObjectFieldDescriptorProto.Size(m)
}
func (m *ObjectFieldDescriptorProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectFieldDescriptorProto.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectFieldDescriptorProto proto.InternalMessageInfo

func (m *ObjectFieldDescriptorProto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ObjectFieldDescriptorProto) GetValue() *ValueDescriptorProto {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*FileDescriptorSet)(nil), "graphqlc.FileDescriptorSet")
	proto.RegisterType((*FileDescriptorGraphql)(nil), "graphqlc.FileDescriptorGraphql")
	proto.RegisterType((*SchemaDescriptorProto)(nil), "graphqlc.SchemaDescriptorProto")
	proto.RegisterType((*ScalarTypeDefinitionDescriptorProto)(nil), "graphqlc.ScalarTypeDefinitionDescriptorProto")
	proto.RegisterType((*ObjectTypeDefinitionDescriptorProto)(nil), "graphqlc.ObjectTypeDefinitionDescriptorProto")
	proto.RegisterType((*InterfaceTypeDefinitionDescriptorProto)(nil), "graphqlc.InterfaceTypeDefinitionDescriptorProto")
	proto.RegisterType((*UnionTypeDefinitionDescriptorProto)(nil), "graphqlc.UnionTypeDefinitionDescriptorProto")
	proto.RegisterType((*EnumTypeDefinitionDescriptorProto)(nil), "graphqlc.EnumTypeDefinitionDescriptorProto")
	proto.RegisterType((*InputObjectTypeDefinitionDescriptorProto)(nil), "graphqlc.InputObjectTypeDefinitionDescriptorProto")
	proto.RegisterType((*EnumValueDefinitionDescription)(nil), "graphqlc.EnumValueDefinitionDescription")
	proto.RegisterType((*FieldDefinitionDescriptorProto)(nil), "graphqlc.FieldDefinitionDescriptorProto")
	proto.RegisterType((*InputValueDefinitionDescriptorProto)(nil), "graphqlc.InputValueDefinitionDescriptorProto")
	proto.RegisterType((*TypeDescriptorProto)(nil), "graphqlc.TypeDescriptorProto")
	proto.RegisterType((*NamedTypeDescriptorProto)(nil), "graphqlc.NamedTypeDescriptorProto")
	proto.RegisterType((*ListTypeDescriptorProto)(nil), "graphqlc.ListTypeDescriptorProto")
	proto.RegisterType((*NonNullTypeDescriptorProto)(nil), "graphqlc.NonNullTypeDescriptorProto")
	proto.RegisterType((*DirectiveDescriptorProto)(nil), "graphqlc.DirectiveDescriptorProto")
	proto.RegisterType((*ArgumentDescriptorProto)(nil), "graphqlc.ArgumentDescriptorProto")
	proto.RegisterType((*ValueDescriptorProto)(nil), "graphqlc.ValueDescriptorProto")
	proto.RegisterType((*VariableDescriptorProto)(nil), "graphqlc.VariableDescriptorProto")
	proto.RegisterType((*NullValueDescriptorProto)(nil), "graphqlc.NullValueDescriptorProto")
	proto.RegisterType((*EnumValueDescriptorProto)(nil), "graphqlc.EnumValueDescriptorProto")
	proto.RegisterType((*ListValueDescriptorProto)(nil), "graphqlc.ListValueDescriptorProto")
	proto.RegisterType((*ObjectValueDescriptorProto)(nil), "graphqlc.ObjectValueDescriptorProto")
	proto.RegisterType((*ObjectFieldDescriptorProto)(nil), "graphqlc.ObjectFieldDescriptorProto")
}

func init() { proto.RegisterFile("graphqlc/descriptor.proto", fileDescriptor_b5c0692a5e3de09d) }

var fileDescriptor_b5c0692a5e3de09d = []byte{
	// 1109 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0x4f, 0x8f, 0xdb, 0x44,
	0x14, 0x5f, 0xe7, 0xdf, 0x26, 0x2f, 0x09, 0x12, 0x43, 0xab, 0x35, 0x95, 0xba, 0xec, 0x7a, 0x01,
	0x45, 0x82, 0xcd, 0x96, 0x16, 0xe8, 0x01, 0x24, 0xda, 0xdd, 0x2d, 0xdd, 0x2d, 0x55, 0x29, 0x29,
	0x14, 0xa9, 0x97, 0xc8, 0x49, 0x26, 0xd9, 0x81, 0xf1, 0x38, 0xb5, 0xc7, 0x8b, 0x96, 0xaf, 0xc1,
	0x01, 0x09, 0x21, 0x71, 0x87, 0x23, 0x77, 0xbe, 0x0a, 0x17, 0x38, 0x71, 0xe1, 0x23, 0xa0, 0xf1,
	0xcc, 0xd8, 0x8e, 0x63, 0x27, 0xae, 0x55, 0x69, 0xb9, 0x25, 0xf3, 0xde, 0xfb, 0xcd, 0x7b, 0xbf,
	0xf7, 0x67, 0x66, 0x0c, 0xaf, 0xcf, 0x3c, 0x7b, 0x7e, 0xf6, 0x9c, 0x8e, 0x0f, 0x26, 0xd8, 0x1f,
	0x7b, 0x64, 0xce, 0x5d, 0xaf, 0x3f, 0xf7, 0x5c, 0xee, 0xa2, 0xa6, 0x16, 0x59, 0x27, 0xf0, 0xea,
	0xa7, 0x84, 0xe2, 0xe3, 0x48, 0xe3, 0x09, 0xe6, 0xe8, 0x16, 0xd4, 0xa6, 0x84, 0x62, 0xd3, 0xd8,
	0xa9, 0xf6, 0xda, 0x37, 0xdf, 0xe8, 0x6b, 0xed, 0xfe, 0xa2, 0xea, 0x7d, 0xb9, 0x3c, 0x08, 0x95,
	0xad, 0x5f, 0x6b, 0x70, 0x35, 0x53, 0x8e, 0x10, 0xd4, 0x98, 0xed, 0x08, 0x38, 0xa3, 0xd7, 0x1a,
	0x84, 0xbf, 0xd1, 0x6d, 0x68, 0xf8, 0xe3, 0x33, 0xec, 0xd8, 0x66, 0x65, 0xc7, 0x58, 0xdc, 0xe4,
	0x49, 0xb8, 0x1e, 0xc3, 0x3c, 0x16, 0x2e, 0x0f, 0x94, 0x3a, 0xba, 0x0f, 0x9b, 0xfe, 0xd8, 0xa6,
	0xb6, 0xe7, 0x9b, 0xd5, 0xd0, 0xbd, 0xfd, 0xa4, 0xa5, 0x10, 0x7c, 0x79, 0x31, 0xc7, 0xc7, 0x78,
	0x4a, 0x18, 0xe1, 0xc4, 0x65, 0x69, 0x1c, 0x6d, 0x2d, 0x80, 0xdc, 0xd1, 0x37, 0x78, 0xcc, 0x7d,
	0xb3, 0x96, 0x06, 0xfa, 0x3c, 0x14, 0xac, 0x01, 0x52, 0xd6, 0xe8, 0x31, 0x00, 0x61, 0x1c, 0x7b,
	0x53, 0x7b, 0x8c, 0x7d, 0xb3, 0x1e, 0x62, 0xdd, 0x88, 0xb1, 0x4e, 0xb5, 0x6c, 0x35, 0x5c, 0x02,
	0x03, 0x1d, 0x43, 0x23, 0x60, 0xc4, 0x65, 0xbe, 0xd9, 0x08, 0xd1, 0xde, 0x8d, 0xd1, 0xbe, 0x12,
	0xeb, 0xab, 0x91, 0x94, 0x2d, 0xba, 0x0b, 0x75, 0xcc, 0x02, 0xc7, 0x37, 0x37, 0x43, 0x90, 0x77,
	0x62, 0x90, 0x7b, 0x2c, 0x70, 0x56, 0x63, 0x48, 0x4b, 0xf4, 0x35, 0x74, 0x09, 0x9b, 0x07, 0x7c,
	0xa8, 0x99, 0x6a, 0x86, 0x50, 0x37, 0x93, 0xd1, 0xcd, 0x03, 0x5e, 0x84, 0xae, 0x0e, 0x89, 0x35,
	0x7d, 0xeb, 0x8f, 0x0a, 0x5c, 0xcd, 0xcc, 0x33, 0x3a, 0x04, 0x98, 0x10, 0x0f, 0x8f, 0x39, 0x39,
	0xc7, 0xbe, 0xaa, 0x40, 0x2b, 0xde, 0xef, 0x58, 0xcb, 0x96, 0xf8, 0x8b, 0xad, 0xd0, 0x11, 0xd4,
	0x9f, 0x07, 0xd8, 0xbb, 0x50, 0xb5, 0xf5, 0x82, 0x89, 0x95, 0xb6, 0xe8, 0x14, 0x9a, 0x4e, 0xc0,
	0x6d, 0xa1, 0x61, 0x56, 0xcb, 0xe0, 0x44, 0xe6, 0xe8, 0x0b, 0xe8, 0xf8, 0xc1, 0x48, 0x4a, 0x05,
	0x5c, 0xad, 0x0c, 0xdc, 0x02, 0x84, 0xf5, 0x8b, 0x01, 0x7b, 0x05, 0xca, 0x1d, 0xed, 0x40, 0x5b,
	0x77, 0xbf, 0xd8, 0x59, 0xb6, 0x60, 0x72, 0x29, 0xea, 0xce, 0x4a, 0xa2, 0x3b, 0x17, 0x93, 0x50,
	0x2d, 0x93, 0x04, 0xeb, 0xf7, 0x0a, 0xec, 0x15, 0x88, 0xab, 0xa4, 0x87, 0xa2, 0xe9, 0x9c, 0x39,
	0xc5, 0x0e, 0x66, 0x5c, 0x7b, 0x58, 0xa6, 0xe9, 0x22, 0x8c, 0x54, 0xcc, 0xb5, 0x52, 0x85, 0x77,
	0x07, 0x1a, 0x53, 0x82, 0xe9, 0x44, 0x8f, 0x81, 0x5e, 0x72, 0x74, 0x62, 0x3a, 0x59, 0xd1, 0xb4,
	0xd2, 0xce, 0xfa, 0xcb, 0x80, 0xb7, 0x8b, 0x39, 0x7f, 0x79, 0xa9, 0x4d, 0x84, 0x59, 0x2b, 0x19,
	0xe6, 0xdf, 0x06, 0x58, 0xeb, 0x47, 0xd9, 0x25, 0x86, 0x78, 0x0f, 0x3a, 0x0e, 0x76, 0x46, 0xd8,
	0x1b, 0xf2, 0x8b, 0x79, 0x56, 0x3d, 0x3c, 0xb2, 0x1d, 0x3c, 0x91, 0xde, 0x2f, 0xa2, 0xb4, 0xa5,
	0x9d, 0x10, 0xf9, 0xd6, 0x9f, 0x06, 0xec, 0xae, 0x9d, 0xb6, 0x97, 0x9b, 0xc9, 0x73, 0x9b, 0x06,
	0x38, 0x23, 0x93, 0xc2, 0xed, 0xa7, 0x42, 0xb6, 0xec, 0x37, 0x71, 0xd9, 0x40, 0xd9, 0x59, 0xff,
	0x18, 0xd0, 0x2b, 0x7a, 0x08, 0x5c, 0x6a, 0x3e, 0x17, 0x4b, 0x76, 0x3f, 0x75, 0x84, 0xe5, 0x44,
	0x9a, 0xae, 0xdb, 0x9f, 0x0d, 0xd8, 0x5e, 0x4d, 0x4c, 0x81, 0x18, 0xaf, 0x40, 0x3d, 0x24, 0x4f,
	0x05, 0x29, 0xff, 0xbc, 0x94, 0x99, 0xfb, 0x53, 0x05, 0xb6, 0x57, 0x77, 0x60, 0xc9, 0x14, 0x7c,
	0x06, 0x2d, 0xdb, 0x9b, 0x05, 0xc9, 0x69, 0xfb, 0x82, 0x0c, 0xc6, 0xf6, 0xe8, 0x3d, 0xa8, 0x89,
	0xa6, 0x52, 0xc7, 0xe0, 0xf5, 0x18, 0x27, 0xab, 0x9d, 0x42, 0xd5, 0x14, 0x39, 0xf5, 0x52, 0xe4,
	0xfc, 0x58, 0x81, 0xbd, 0x02, 0x9e, 0x96, 0x64, 0x48, 0x07, 0x55, 0x2d, 0x1e, 0xd4, 0x11, 0x74,
	0x27, 0x78, 0x6a, 0x07, 0x94, 0x0f, 0x65, 0x3d, 0x48, 0x42, 0xb6, 0x63, 0x5b, 0xe5, 0x69, 0xea,
	0x22, 0xa0, 0x8c, 0x9e, 0x66, 0x94, 0x4d, 0x39, 0x66, 0xfe, 0x35, 0xe0, 0xb5, 0x0c, 0x37, 0xd1,
	0x11, 0x80, 0x88, 0x6d, 0x12, 0xce, 0xc0, 0x90, 0x88, 0x42, 0x23, 0xf0, 0x64, 0x63, 0xd0, 0x62,
	0x5a, 0x86, 0xee, 0x40, 0x8b, 0x12, 0x9f, 0x4b, 0x0c, 0x79, 0x21, 0xdb, 0x8d, 0x31, 0x1e, 0x12,
	0x9f, 0x67, 0x43, 0x34, 0xa9, 0x12, 0xa1, 0x07, 0xd0, 0x65, 0x2e, 0x1b, 0xb2, 0x80, 0xd2, 0x61,
	0x82, 0xe3, 0x37, 0x13, 0x9e, 0xb8, 0xec, 0x51, 0x40, 0x69, 0x36, 0x50, 0x9b, 0xc5, 0xd2, 0xc3,
	0x86, 0x4c, 0x93, 0xd5, 0x07, 0x33, 0xcf, 0xfd, 0xac, 0xf7, 0x8a, 0xf5, 0x10, 0xb6, 0x72, 0x5c,
	0x8d, 0x32, 0x6f, 0x14, 0xce, 0xbc, 0xf5, 0x9b, 0x01, 0xd7, 0xf2, 0x7d, 0xfe, 0x9f, 0xf0, 0x1e,
	0x71, 0xe5, 0x82, 0x99, 0x57, 0x46, 0x99, 0x6f, 0xbb, 0x4f, 0x92, 0xc3, 0xa2, 0x12, 0x56, 0x64,
	0x62, 0xe7, 0xbb, 0x4a, 0x94, 0x3f, 0x20, 0xac, 0x31, 0x6c, 0xe5, 0x68, 0x65, 0xee, 0xf7, 0x7e,
	0x72, 0x9e, 0xae, 0xef, 0x1f, 0xa9, 0x6c, 0xfd, 0x50, 0x83, 0x2b, 0x59, 0x72, 0xf4, 0x00, 0x5e,
	0x39, 0xb7, 0x3d, 0x62, 0x8f, 0x28, 0x1e, 0x26, 0x71, 0x77, 0x93, 0xb8, 0x52, 0xbe, 0xcc, 0x5e,
	0x57, 0x9b, 0xca, 0xee, 0xbc, 0x0e, 0x2d, 0xc2, 0x74, 0x7b, 0x8b, 0xb2, 0xad, 0x0b, 0x86, 0x09,
	0x53, 0xcd, 0xbb, 0x0b, 0xed, 0x29, 0x75, 0xed, 0x64, 0xff, 0x57, 0x4e, 0x36, 0x06, 0x10, 0x2e,
	0x4a, 0x95, 0xb7, 0xa0, 0x3b, 0x72, 0x5d, 0x8a, 0x6d, 0xa6, 0x94, 0xea, 0x3b, 0x46, 0xaf, 0x79,
	0xb2, 0x31, 0xe8, 0xa8, 0x65, 0xa9, 0xb6, 0x07, 0x1d, 0x9f, 0x7b, 0x84, 0xcd, 0x94, 0x56, 0x43,
	0xf0, 0x23, 0x8a, 0x5f, 0xae, 0x4a, 0x25, 0x51, 0x57, 0xa2, 0x89, 0xa4, 0xca, 0xe6, 0x52, 0x5d,
	0x05, 0x94, 0x66, 0x31, 0x12, 0xd6, 0x95, 0x96, 0x09, 0x10, 0xf1, 0x38, 0x54, 0x20, 0xcd, 0x34,
	0x48, 0xe2, 0x74, 0x5c, 0x02, 0xc1, 0x5a, 0x26, 0x40, 0xc2, 0xe2, 0x94, 0x20, 0xad, 0x34, 0x88,
	0xa8, 0xce, 0x3c, 0x10, 0xaa, 0x65, 0xe8, 0x14, 0x3a, 0xf2, 0x5d, 0xaa, 0x60, 0x20, 0x3d, 0x16,
	0xe4, 0x95, 0x24, 0x07, 0xa8, 0xed, 0xc6, 0xd2, 0xc3, 0x4d, 0x55, 0x42, 0xd6, 0x3e, 0x6c, 0xe5,
	0x24, 0x37, 0x73, 0x2c, 0xdc, 0x00, 0x33, 0x8f, 0xb5, 0xf8, 0x98, 0x37, 0x12, 0xc7, 0xbc, 0xb0,
	0xc8, 0xa3, 0x28, 0xc7, 0x62, 0x00, 0x66, 0x1e, 0x1f, 0xe8, 0xc3, 0xe8, 0xfe, 0x26, 0x5f, 0xca,
	0xeb, 0x6a, 0x5f, 0xdf, 0xda, 0x9e, 0xc1, 0xb5, 0x7c, 0x72, 0xd0, 0xc7, 0xd1, 0x65, 0x49, 0xa2,
	0x2e, 0x51, 0xaa, 0xee, 0x18, 0xd9, 0x77, 0xa4, 0xa9, 0xc6, 0xce, 0xd2, 0x7a, 0x79, 0x0d, 0x7c,
	0x78, 0xfb, 0xd9, 0x07, 0x33, 0xc2, 0xcf, 0x82, 0x51, 0x7f, 0xec, 0x3a, 0x07, 0xbe, 0xed, 0x50,
	0xc2, 0xdd, 0xef, 0x08, 0xff, 0xfe, 0x20, 0xfa, 0xf0, 0x35, 0xff, 0x76, 0x16, 0xfd, 0xf9, 0x48,
	0xff, 0x18, 0x35, 0xc2, 0x8f, 0x60, 0xb7, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xdc, 0x59,
	0x9b, 0x21, 0x13, 0x00, 0x00,
}
