package graphqlc

type DirectiveLocationDescriptorProto_Location = isDirectiveLocationDescriptorProto_Location
type NonNullTypeDescriptorProto_Type = isNonNullTypeDescriptorProto_Type
type TypeDescriptorProto_Type = isTypeDescriptorProto_Type
type ValueDescriptorProto_Value = isValueDescriptorProto_Value
